#!/bin/bash

# This script runs the Go tests for the project.
# Usage: ./.github/scripts/go_tests.sh

go clean -testcache

# Priority
go test ./smt/pkg/...
go test ./zk/da/...
go test ./zk/debug_tools/...
go test ./zk/hermez_db/...
go test ./zk/l1_data/...
go test ./zk/l1infotree/...
go test ./zk/legacy_executor_verifier/...
go test ./zk/metrics/...
go test ./zk/smt/...
go test ./zk/stages/...
go test ./zk/syncer/...
go test ./zk/tests/...
go test ./zk/tx/...
go test ./zk/types/...
go test ./zk/utils/...
go test ./zk/witness/...
go test ./zkevm/...

cd erigon-lib/
go test ./...
cd ..

# All
go test ./accounts/...
go test ./cmd/...
go test ./common/...
go test ./consensus/...
go test ./core/...
go test ./crypto/...
go test ./ethdb/privateapi/...
go test ./eth/...
go test ./event/...
go test ./migrations/...
go test ./node/...
go test ./p2p/...
go test ./params/...
go test ./polygon/...
go test ./rlp/...
go test ./rpc/...
go test ./tests/...
go test ./turbo/builder/...
go test ./turbo/execution/...
go test ./turbo/rlphacks/...
go test ./turbo/rpchelper/...
go test ./turbo/shards/...
go test ./turbo/snapshotsync/...
go test ./turbo/stages/...
go test ./turbo/trie/...

go test ./cl/abstract/...
go test ./cl/aggregation/...
go test ./cl/antiquary/...
go test ./cl/beacon/...
go test ./cl/clparams/...
go test ./cl/clstages/...
go test ./cl/cltypes/...
go test ./cl/fork/...
go test ./cl/gossip/...
go test ./cl/merkle_tree/...
go test ./cl/persistence/...
go test ./cl/phase1/...
go test ./cl/pool/...
go test ./cl/rpc/...
go test ./cl/spectest/...
go test ./cl/ssz/...
go test ./cl/transition/...
go test ./cl/utils/...
go test ./cl/validator/...

# TODO - fix these tests
# go test ./zk/apollo/...
# go test ./zk/datastream/...
# go test ./zk/txpool/...
# go test ./ethdb/prune/...
# go test ./ci/e2e-1/...
# go test ./test/e2e/...
# go test ./turbo/jsonrpc/...
# go test ./cl/sentinel/...