#!/bin/bash

# This script runs the Go tests for the project.
# Usage: ./.github/scripts/go_tests.sh

go clean -testcache

# Priority
go test ./smt/pkg/...
go test ./zk/da/...
go test ./zk/debug_tools/...
go test ./zk/hermez_db/...
go test ./zk/l1_data/...
go test ./zk/l1infotree/...
go test ./zk/legacy_executor_verifier/...
go test ./zk/metrics/...
go test ./zk/smt/...
go test ./zk/stages/...
go test ./zk/syncer/...
go test ./zk/tests/...
go test ./zk/tx/...
go test ./zk/types/...
go test ./zk/utils/...
go test ./zk/witness/...
go test ./zkevm/...

cd erigon-lib/
go test ./...
cd ..

# All
go test ./accounts/...


# TODO - fix these tests
# go test ./zk/apollo/...
# go test ./zk/datastream/...
# go test ./zk/txpool/...