networks:
  default:
    name: erigon
services:
  xlayer-approve:
    container_name: xlayer-approve
    image: hermeznetwork/zkevm-node:v0.6.6
    volumes:
      - ./keystore/sequencer.keystore:/pk/keystore
      - ./config/test.node.config.toml:/app/config.toml
      - ./config/test.genesis.config.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-node approve --network custom --custom-network-file /app/genesis.json --key-store-path /pk/keystore --pw testonly --am 115792089237316195423570985008687907853269984665640564039457584007913129639935 -y --cfg /app/config.toml"

  xlayer-seq:
    container_name: xlayer-seq
    image: cdk-erigon
    environment:
      - CDK_ERIGON_SEQUENCER=1
      - WRITE_MAP=true
    ports:
      - 6060:6060
      - 8123:8545
      - 6900:6900
      - 9092:9095
    volumes:
      - ./data/seq/:/home/erigon/data/
      - ./config/test.erigon.seq.config.yaml:/usr/src/app/config.yaml
      - ./config/first-batch-config.json:/usr/src/app/first-batch-config.json
      - ./config/dynamic-mynetwork-allocs.json:/usr/src/app/dynamic-mynetwork-allocs.json
      - ./config/dynamic-mynetwork-chainspec.json:/usr/src/app/dynamic-mynetwork-chainspec.json
      - ./config/dynamic-mynetwork-conf.json:/usr/src/app/dynamic-mynetwork-conf.json
    command: >
      cdk-erigon --http.vhosts=* --http.corsdomain=* --ws --config=/usr/src/app/config.yaml

  xlayer-mock-l1-network:
    container_name: xlayer-mock-l1-network
    image: zjg555543/geth:pp-v5
    ports:
      - 8545:8545
      - 8546:8546
    command:
      - "--http"
      - "--http.api"
      - "admin,eth,debug,miner,net,txpool,personal,web3"
      - "--http.addr"
      - "0.0.0.0"
      - "--http.corsdomain"
      - "*"
      - "--http.vhosts"
      - "*"
      - "--ws"
      - "--ws.origins"
      - "*"
      - "--ws.addr"
      - "0.0.0.0"
      - "--dev"
      - "--dev.period"
      - "1"
      - "--datadir"
      - "/geth_data"
      - "--syncmode"
      - "full"
      - "--rpc.allow-unprotected-txs"

  xlayer-bridge-db:
    container_name: xlayer-bridge-db
    image: postgres:15
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    ports:
      - 5439:5432
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_DB=test_db
    command: [ "postgres", "-N", "500" ]

  xlayer-bridge-service:
    container_name: xlayer-bridge-service
    image: hermeznetwork/zkevm-bridge-service:v0.6.0-RC16
    ports:
      - 8080:8080
      - 9090:9090
    environment:
      - ZKEVM_BRIDGE_DATABASE_USER=test_user
      - ZKEVM_BRIDGE_DATABASE_PASSWORD=test_password
      - ZKEVM_BRIDGE_DATABASE_NAME=test_db
      - ZKEVM_BRIDGE_DATABASE_HOST=xlayer-bridge-db
      - ZKEVM_BRIDGE_DATABASE_PORT=5432
    volumes:
      - ./keystore/sequencer.keystore:/pk/keystore.claimtxmanager
      - ./config/test.bridge.config.toml:/app/config.toml
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-bridge run --cfg /app/config.toml"

  xlayer-bridge-ui:
    container_name: xlayer-bridge-ui
    image: hermeznetwork/zkevm-bridge-ui:latest
    ports:
      - 8090:80
    environment:
      - ETHEREUM_RPC_URL=http://127.0.0.1:8545
      - ETHEREUM_EXPLORER_URL=http://127.0.0.1:4000
      - ETHEREUM_ROLLUP_MANAGER_ADDRESS=0xE96dBF374555C6993618906629988d39184716B3
      - ETHEREUM_BRIDGE_CONTRACT_ADDRESS=0x4B24266C13AFEf2bb60e2C69A4C08A482d81e3CA
      - ETHEREUM_FORCE_UPDATE_GLOBAL_EXIT_ROOT=true
      - ETHEREUM_PROOF_OF_EFFICIENCY_CONTRACT_ADDRESS=0xE45CCD0757670580a4a3600DE5cef1e45F0Ec2bd
      - POLYGON_ZK_EVM_RPC_URL=http://127.0.0.1:8123
      - POLYGON_ZK_EVM_EXPLORER_URL=http://127.0.0.1:4001
      - POLYGON_ZK_EVM_BRIDGE_CONTRACT_ADDRESS=0x4B24266C13AFEf2bb60e2C69A4C08A482d81e3CA
      - POLYGON_ZK_EVM_NETWORK_ID=1
      - BRIDGE_API_URL=http://127.0.0.1:8080
      - ENABLE_FIAT_EXCHANGE_RATES=false
      - ENABLE_OUTDATED_NETWORK_MODAL=false
      - ENABLE_DEPOSIT_WARNING=false
      - ENABLE_REPORT_FORM=false
      - RESOLVE_RELATIVE_URLS=false

  zkevm-mock-l1-network:
    container_name: zkevm-mock-l1-network
    # This image contains the contracts upgraded to Feijoa, disabled 
    image: hermeznetwork/geth-zkevm-contracts:1.5-integration
    # image: hermeznetwork/geth-zkevm-contracts:v2.1.3-fork.8-geth1.12.0
    ports:
      - 8545:8545
      - 8546:8546
    command:
      - "--http"
      - "--http.api"
      - "admin,eth,debug,miner,net,txpool,personal,web3"
      - "--http.addr"
      - "0.0.0.0"
      - "--http.corsdomain"
      - "*"
      - "--http.vhosts"
      - "*"
      - "--ws"
      - "--ws.origins"
      - "*"
      - "--ws.addr"
      - "0.0.0.0"
      - "--dev"
      - "--dev.period"
      - "1"
      - "--datadir"
      - "/geth_data"
      - "--syncmode"
      - "full"
      - "--rpc.allow-unprotected-txs"

  xlayer-pool-db:
    container_name: xlayer-pool-db
    image: postgres:15
    ports:
      - 5440:5432
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_USER=pool_user
      - POSTGRES_PASSWORD=pool_password
      - POSTGRES_DB=pool_db
    command:
      - "postgres"
      - "-N"
      - "500"

  xlayer-pool-manager:
    container_name: xlayer-pool-manager
    image: hermeznetwork/zkevm-pool-manager:v0.1.2
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    ports:
      - 8125:8545
    volumes:
      - ./config/test.poolmanager.toml:/app/poolmanager.toml
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-pool-manager run --cfg /app/poolmanager.toml"

  xlayer-cdk-node:
    container_name: xlayer-cdk-node
    image: zjg555543/cdk:v0.5.4-rc1
    restart: on-failure
    volumes:
      - ./data/cdk-node:/tmp
      - ./keystore/aggregator.keystore:/etc/cdk/aggregator.keystore
      - ./keystore/sequencer.keystore:/etc/cdk/sequencer.keystore
      - ./config/cdk-node-config.toml:/etc/cdk/cdk-node-config.toml
      - ./config/test.genesis.config.json:/etc/cdk/genesis.json
    ports:
      - 5576:5576
    command:
      - "/bin/sh"
      - "-c"
      - "cdk-node run --cfg=/etc/cdk/cdk-node-config.toml --custom-network-file=/etc/cdk/genesis.json --save-config-path=/tmp/ --components=aggsender"

  xlayer-agglayer:
    container_name: xlayer-agglayer
    image: zjg555543/agglayer:v0.3.0-rc.16
    ports:
      - 4443:4443
      - 4444:4444
      - 4446:4446
      - 9094:9092
    volumes:
      - ./keystore/agglayer.keystore:/etc/zkevm/agglayer.keystore
      - ./config/agglayer-config.toml:/etc/zkevm/agglayer-config.toml
      - ./data/agglayer/storage:/etc/zkevm/storage/
      - ./data/agglayer/backups:/etc/zkevm/backups/
    command:
      - "/bin/sh"
      - "-c"
      - "/usr/local/bin/agglayer run --cfg /etc/zkevm/agglayer-config.toml"

  xlayer-agglayer-prover:
    container_name: xlayer-agglayer-prover
    image: zjg555543/agglayer:v0.3.0-rc.16
    volumes:
      - ./config/agglayer-prover-config.toml:/etc/zkevm/agglayer-prover-config.toml
    ports:
      - 4445:4445
      - 9093:9093
    command:
      - "/bin/sh"
      - "-c"
      - "/usr/local/bin/agglayer prover --cfg /etc/zkevm/agglayer-prover-config.toml"

  xlayer-agg-db:
    container_name: xlayer-agg-db
    image: postgres:15
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=aggregator_user
      - POSTGRES_PASSWORD=aggregator_password
      - POSTGRES_DB=aggregator_db
    command:
      - "postgres"
      - "-N"
      - "500"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aggregator_user -d aggregator_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  xlayer-rpc:
    container_name: xlayer-rpc
    image: cdk-erigon
    environment:
      - CDK_ERIGON_SEQUENCER=0
      - WRITE_MAP=true
    ports:
      - 6061:6060
      - 8124:8545
      - 6901:6900
      - 9091:9095
    volumes:
      - ./data/rpc/:/home/erigon/data/
      - ./config/test.erigon.rpc.config.yaml:/usr/src/app/config.yaml
      - ./config/first-batch-config.json:/usr/src/app/first-batch-config.json
      - ./config/dynamic-mynetwork-allocs.json:/usr/src/app/dynamic-mynetwork-allocs.json
      - ./config/dynamic-mynetwork-chainspec.json:/usr/src/app/dynamic-mynetwork-chainspec.json
      - ./config/dynamic-mynetwork-conf.json:/usr/src/app/dynamic-mynetwork-conf.json
    command: >
      cdk-erigon --http.vhosts=* --http.corsdomain=* --ws --config=/usr/src/app/config.yaml